=== amitnautiyalcsf/Xml-Schema-Definition-and-Its-Validation/xmlSchemaDemo/src/orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://myorders.com/orders"
	xmlns:orders="http://myorders.com/orders"
	elementFormDefault="qualified">

	<element name="orders">
		<complexType>
			<sequence>

				<element name="order" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="productId" type="int" minOccurs="1"
								maxOccurs="1"></element>
							<element name="productName" type="string"></element>
							<element name="description" type="string"></element>
							<element name="price" type="double"></element>
							<element name="imageUrl" type="string"></element>
							<element name="availability" type="date"></element>
							<element name="rating" type="double"></element>
						</sequence>



					</complexType>


				</element>


			</sequence>
		</complexType>
	</element>


</schema>

=== amitnautiyalcsf/Xml-Schema-Definition-and-Its-Validation/xmlSchemaDemo/bin/orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<orders xmlns="http://myorders.com/orders"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://myorders.com/orders orders.xsd ">
	<order>
		<productId>1</productId>
		<productName>iphone</productName>
		<description>IphoneX</description>
		<price>100000</price>
		<imageUrl>https://apple/iphone.com</imageUrl>
		<availability>2019-01-01</availability>
		<rating>4.5</rating>
	</order>
</orders>
